### ISSUE TITLE
Updated docker image?

### ISSUE THREAD

**Issue by ptqa** [carlpett/stream_exporter#12]
Hi. Thanks for this project! 

Is there any reason why docker image is not updated by circleci? It seems like there is a stage for that in circleci, but not in Makefile.

**Comment by carlpett** [comment]
Very good question... I'll look into it!

**Comment by carlpett** [comment]
Now it should be up :) Both the CircleCI config and the Docker Hub config had gotten old, but are now updated!

**Comment by ptqa** [comment]
Thanks!
