### ISSUE TITLE
Input type stdin?

### ISSUE THREAD

**Issue by sepich** [carlpett/stream_exporter#14]
Hello,
Could you please add input type `stdin`?
That would be useful to make stream_explorer working with `program` destination of syslog-ng:
https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.19/administration-guide/41#TOPIC-1094619
And for simplest debug or `sh -c 'myprog | stream_explorer'` cases.
Thank you.

**Comment by carlpett** [comment]
Hi @sepich,
This should be fairly easy. How would you expect it to treat end-of-file for the debug case? Exiting, or staying around?
Regarding the syslog-ng program destination, are you aware that the exporter already supports syslog input?

**Comment by sepich** [comment]
>This should be fairly easy.

Great!

>How would you expect it to treat end-of-file for the debug case? Exiting, or staying around?

It seems the only option in this case is exiting, as default handler action of the SIGPIPE signal is to terminate. And that sounds fine.

>Regarding the syslog-ng program destination, are you aware that the exporter already supports syslog input?

Sure, that's how i use it now - as a sidecar container in k8s in `syslog` pod. Syslog then forwards some events to `localhost:1514`. 
That works fine, point of this feature request - is to simplify such a setup. So, that syslog-ng would start stream_exporter as a child process inside the same single container. Sorry, not mentioning this on a first place.

**Comment by carlpett** [comment]
>It seems the only option in this case is exiting, as default handler action of the SIGPIPE signal is to terminate. And that sounds fine.

Hm, I don't believe we'd get a SIGPIPE when stdin is closed, right? If we'd been writing to stdout and it was closed, I'd expect a SIGPIPE, but not here, when we are reading?
With the current code, the exporter will stay around and accept requests to /metrics, but there will be no more input accepted. But then you'd need to ensure you signal it to quit yourself.

**Comment by sepich** [comment]
I've tested branch `input-stdin` with such Dockerfile
```
FROM golang:1.8 as build
RUN go get -u github.com/kardianos/govendor
RUN mkdir -p /go/src/github.com/carlpett/ && \
    cd /go/src/github.com/carlpett/ && \
    git clone https://github.com/carlpett/stream_exporter.git && \
    cd stream_exporter && \
    git checkout input-stdin
WORKDIR /go/src/github.com/carlpett/stream_exporter
RUN govendor build +p

...
COPY --from=build  /go/src/github.com/carlpett/stream_exporter/stream_exporter /usr/bin/stream_exporter
```
And `syslog-ng` config destination
```
        destination {
            program("stream_exporter -input.type stdin -config /etc/syslog-ng/stream_exporter.yaml");
        };
```
Result in container:
```
root@syslog-8b75f65b6-lz2xv:/# ps auxf
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          1  0.0  0.0 367352  6552 ?        Ss   08:30   0:00 /usr/sbin/syslog-ng -F
root         13  0.0  0.0   4288   668 ?        S    08:30   0:00 /bin/sh -c stream_exporter -input.type stdin -config /etc/syslog-ng/stream_exporter.yaml
root         14  0.0  0.0 348960 10380 ?        Sl   08:30   0:00  \_ stream_exporter -input.type stdin -config /etc/syslog-ng/stream_exporter.yaml
```
Will monitor if there are any change in memory/cpu usage over time. 
Thank you!

P.S
One thing missing in PR - is Readme update ;)

**Comment by carlpett** [comment]
:tada: Thanks for reporting back! Would love some "independent" memory/cpu usage stats if you are able to share.

Good point, I will update and merge the PR :)
